# Generated by Django 5.2.6 on 2025-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='recomendaciones',
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(default='sin categoria', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
