# Generated by Django 5.2.6 on 2025-10-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_remove_servicio_recomendaciones_servicio_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('manicura', 'Manicure'), ('pedicura', 'Pedicure'), ('estructura', 'Estructura')], max_length=20),
        ),
    ]
