# Generated by Django 5.2.6 on 2025-10-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_servicio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('estructura', 'Estructura')], max_length=20),
        ),
    ]
