# Generated by Django 5.2.6 on 2025-09-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='telefono',
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(default='Sin apellidos', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/'),
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleados_empleado',
        ),
    ]
