# Generated by Django 5.2.6 on 2025-10-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleado_fecha_ingreso_remove_empleado_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fotos',
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados_fotos/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='empleado',
            table=None,
        ),
    ]
