# Generated by Django 5.2.6 on 2025-10-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_remove_empleado_fotos_empleado_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si False el empleado está deshabilitado'),
        ),
    ]
