# Generated by Django 5.2.6 on 2025-10-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
