# Generated by Django 5.2.6 on 2025-10-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_delete_empleado'),
        ('empleados', '0003_remove_empleado_fotos_empleado_foto_and_more'),
        ('productos', '0001_initial'),
        ('reserva', '0002_reserva_fecha'),
        ('servicio', '0002_remove_servicio_recomendaciones_servicio_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('gestora', 'hora', 'fecha'), name='unique_reserva_gestora_hora_fecha'),
        ),
    ]
