# Generated by Django 5.2.6 on 2025-10-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_reserva_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_reserva_gestora_hora_fecha',
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default='2025-10-08'),
            preserve_default=False,
        ),
    ]
