# Generated by Django 5.2.6 on 2025-11-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_pagoreserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoreserva',
            name='referencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
