# Generated by Django 5.2.6 on 2025-11-28 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_reset_token'),
        ('reserva', '0006_pagoreserva_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('metodo', models.CharField(choices=[('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('efectivo', 'Efectivo')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=30, null=True)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_restante', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='reserva.reserva')),
            ],
        ),
    ]
