# Generated by Django 5.2.6 on 2025-11-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoreserva',
            name='tipo_pago',
            field=models.CharField(choices=[('abono', 'Abono'), ('completo', 'Pago Completo'), ('saldo', 'Saldo Restante')], default='abono', max_length=15),
        ),
        migrations.AlterField(
            model_name='pagoreserva',
            name='metodo',
            field=models.CharField(choices=[('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('efectivo', 'Efectivo')], max_length=20),
        ),
    ]
