# Generated by Django 5.2.6 on 2025-10-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_empleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
