# Generated by Django 5.2.6 on 2025-10-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_delete_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si False el cliente está deshabilitado'),
        ),
    ]
