# Generated by Django 5.2.6 on 2025-11-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
