# Generated by Django 5.2.6 on 2025-11-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_uso',
            field=models.BooleanField(default=False, help_text='Marcar si se usa en el estudio / experiencia'),
        ),
        migrations.AddField(
            model_name='producto',
            name='recomendado',
            field=models.BooleanField(default=False, help_text='Marcar como recomendado / más vendido'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ventas',
            field=models.PositiveIntegerField(default=0, help_text='Contador sencillo de ventas'),
        ),
    ]
