"""
Django settings for gisenails project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
from decouple import config
import os
import pymysql

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =======================
# SECURITY CONFIG
# =======================

SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key-change-this")
ENCRYPT_KEY = os.getenv("ENCRYPT_KEY", "q3fnUGonImjGQuumjWB0U5HPKZgu7p9cJXlUyfcF1yE=")

DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS en .env debe existir para evitar errores
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost').split(',')

# =======================
# APPLICATIONS
# =======================

INSTALLED_APPS = [
    'empleados',
    'productos',
    'servicio',
    'inicio',
    'nosotros',
    'reserva',
    'login',
    'clientes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gisenails.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR.parent / 'frontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'login.context_processors.notificaciones_context',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gisenails.wsgi.application'

# =======================
# DATABASE CONFIG
# =======================
# 👉 LOCAL: Usa CleverCloud (todos el equipo comparte la misma BD)
# 👉 PRODUCCIÓN: Usa MySQL del VPS (definido en el .env del servidor)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('MYSQL_ADDON_DB'),
        'USER': config('MYSQL_ADDON_USER'),
        'PASSWORD': config('MYSQL_ADDON_PASSWORD'),
        'HOST': config('MYSQL_ADDON_HOST'),
        'PORT': config('MYSQL_ADDON_PORT', cast=int),
    }
}

# =======================
# AUTH & PASSWORDS
# =======================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =======================
# INTERNATIONALIZATION
# =======================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# =======================
# STATIC & MEDIA FILES
# =======================

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "..", "frontend", "static"),
]


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =======================
# DEFAULT PRIMARY KEY
# =======================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =======================
# JAZZMIN CONFIG
# =======================

JAZZMIN_SETTINGS = {
    "site_title": "Panel de Administración",
    "site_header": "GiseNails",
    "site_brand": "GiseNails",
    "welcome_sign": "Bienvenido al panel de administración",
    "copyright": "GiseNails",
    "search_model": ["empleados.Empleado", "clientes.Cliente", "productos.Producto", "servicios.Servicio"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "custom_links": {
        "empleados": [{
            "name": "Agregar Empleado",
            "url": "empleados_empleado_add",
            "icon": "fas fa-user-plus",
            "permissions": ["empleados.add_empleado"]
        }],
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "brand_colour": "navbar-dark bg-dark",
    "sidebar": "sidebar-dark-primary",
}

# =======================
# LOGIN
# =======================

LOGIN_URL = '/login/login/'

CSRF_FAILURE_VIEW = 'gisenails.views.csrf_failure'

# =======================
# EMAIL CONFIG (SMTP)
# =======================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'gisenails76@gmail.com'
EMAIL_HOST_PASSWORD = 'ltpu mdvi yybw gxic'  # Usa contraseña de aplicación
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'GiseNails <gisenails76@gmail.com>'
